export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'

export const QUESTIONS_FETCHED = 'QUESTIONS_FETCHED'
export const NEXT_QUESTION = 'NEXT_QUESTION'
export const PREVIOUS_QUESTION = 'PREVIOUS_QUESTION'
export const INCREASE_SCORE = 'INCREASE_SCORE'
export const DECREASE_SCORE = 'DECREASE_SCORE'
export const RESET_GAME = 'RESET_GAME'
export const FINISH_GAME = 'FINISH_GAME'

export const IS_LOADING = 'IS_LOADING'
export const IS_NOT_LOADING = 'IS_NOT_LOADING'

export const QUESTIONS_FETCHING = 'QUESTIONS_FETCHING'
export const QUESTIONS_ERROR = 'QUESTIONS_ERROR'
